name: WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Readme Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_LANGUAGE: "true"
          SHOW_TIMEZONE: "true"
          SHOW_OS: "true"
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "false"
